"""
Demo data for development/testing when SofaScore API is unreachable.
"""

DEMO_LIVE_EVENTS = [
    {
        "id": 12345678,
        "homeTeam": {"id": 2697, "name": "Paris Saint-Germain"},
        "awayTeam": {"id": 2721, "name": "Marseille"},
        "homeScore": {"current": 2},
        "awayScore": {"current": 1},
        "status": {"type": "inprogress", "description": "67'"},
        "time": {"currentPeriodStartTimestamp": 1711464000},
        "startTimestamp": 1711461600,
        "tournament": {"name": "Ligue 1", "category": {"name": "France", "alpha2": "fr"}, "uniqueTournament": {"id": 34}},
        "roundInfo": {"round": 28},
        "slug": "paris-saint-germain-marseille",
    },
    {
        "id": 12345679,
        "homeTeam": {"id": 2817, "name": "Real Madrid"},
        "awayTeam": {"id": 2829, "name": "FC Barcelona"},
        "homeScore": {"current": 1},
        "awayScore": {"current": 1},
        "status": {"type": "inprogress", "description": "45+2'"},
        "time": {"currentPeriodStartTimestamp": 1711464000},
        "startTimestamp": 1711461600,
        "tournament": {"name": "La Liga", "category": {"name": "Espagne", "alpha2": "es"}, "uniqueTournament": {"id": 8}},
        "roundInfo": {"round": 30},
        "slug": "real-madrid-fc-barcelona",
    },
]

DEMO_SCHEDULED_EVENTS = [
    {
        "id": 12345680,
        "homeTeam": {"id": 2692, "name": "Manchester City"},
        "awayTeam": {"id": 2686, "name": "Liverpool"},
        "homeScore": {"current": None},
        "awayScore": {"current": None},
        "status": {"type": "notstarted", "description": ""},
        "startTimestamp": 1711476000,
        "tournament": {"name": "Premier League", "category": {"name": "Angleterre", "alpha2": "gb"}, "uniqueTournament": {"id": 17}},
        "roundInfo": {"round": 31},
        "slug": "manchester-city-liverpool",
    },
    {
        "id": 12345681,
        "homeTeam": {"id": 2833, "name": "Bayern Munich"},
        "awayTeam": {"id": 2837, "name": "Borussia Dortmund"},
        "homeScore": {"current": None},
        "awayScore": {"current": None},
        "status": {"type": "notstarted", "description": ""},
        "startTimestamp": 1711479600,
        "tournament": {"name": "Bundesliga", "category": {"name": "Allemagne", "alpha2": "de"}, "uniqueTournament": {"id": 35}},
        "roundInfo": {"round": 27},
        "slug": "bayern-munich-borussia-dortmund",
    },
    {
        "id": 12345682,
        "homeTeam": {"id": 2942, "name": "Juventus"},
        "awayTeam": {"id": 2943, "name": "Inter Milan"},
        "homeScore": {"current": None},
        "awayScore": {"current": None},
        "status": {"type": "notstarted", "description": ""},
        "startTimestamp": 1711483200,
        "tournament": {"name": "Serie A", "category": {"name": "Italie", "alpha2": "it"}, "uniqueTournament": {"id": 23}},
        "roundInfo": {"round": 31},
        "slug": "juventus-inter-milan",
    },
    {
        "id": 12345683,
        "homeTeam": {"id": 2697, "name": "Paris Saint-Germain"},
        "awayTeam": {"id": 2718, "name": "Lyon"},
        "homeScore": {"current": None},
        "awayScore": {"current": None},
        "status": {"type": "notstarted", "description": ""},
        "startTimestamp": 1711486800,
        "tournament": {"name": "Ligue 1", "category": {"name": "France", "alpha2": "fr"}, "uniqueTournament": {"id": 34}},
        "roundInfo": {"round": 28},
        "slug": "paris-saint-germain-lyon",
    },
]

DEMO_MATCH_12345678 = {
    "summary": {
        "id": 12345678,
        "home_team": "Paris Saint-Germain",
        "home_team_id": 2697,
        "home_logo": "https://api.sofascore.com/api/v1/team/2697/image",
        "away_team": "Marseille",
        "away_team_id": 2721,
        "away_logo": "https://api.sofascore.com/api/v1/team/2721/image",
        "home_score": 2,
        "away_score": 1,
        "status_type": "inprogress",
        "status_desc": "67'",
        "start_timestamp": 1711461600,
        "tournament": "Ligue 1",
        "category": "France",
        "country_flag": "fr",
        "round": 28,
    },
    "statistics": {
        "ALL_ball_possession": {"name": "Possession", "home": "64%", "away": "36%", "home_value": 64, "away_value": 36},
        "ALL_total_shots": {"name": "Tirs totaux", "home": "12", "away": "7", "home_value": 12, "away_value": 7},
        "ALL_shots_on_goal": {"name": "Tirs cadrés", "home": "6", "away": "3", "home_value": 6, "away_value": 3},
        "ALL_big_chances": {"name": "Grandes occasions", "home": "4", "away": "1", "home_value": 4, "away_value": 1},
        "ALL_expected_goals": {"name": "Expected Goals (xG)", "home": "2.3", "away": "0.9", "home_value": 2.3, "away_value": 0.9},
        "ALL_corner_kicks": {"name": "Corners", "home": "7", "away": "2", "home_value": 7, "away_value": 2},
        "ALL_fouls": {"name": "Fautes", "home": "8", "away": "14", "home_value": 8, "away_value": 14},
        "ALL_dangerous_attacks": {"name": "Attaques dangereuses", "home": "68", "away": "31", "home_value": 68, "away_value": 31},
        "ALL_attacks": {"name": "Attaques", "home": "112", "away": "67", "home_value": 112, "away_value": 67},
        "ALL_yellow_cards": {"name": "Cartons jaunes", "home": "1", "away": "3", "home_value": 1, "away_value": 3},
        "ALL_free_kicks": {"name": "Coups francs", "home": "14", "away": "8", "home_value": 14, "away_value": 8},
        "ALL_goalkeeper_saves": {"name": "Arrêts gardien", "home": "2", "away": "4", "home_value": 2, "away_value": 4},
        "1ST_ball_possession": {"name": "Possession 1MT", "home": "61%", "away": "39%", "home_value": 61, "away_value": 39},
        "1ST_total_shots": {"name": "Tirs totaux 1MT", "home": "7", "away": "4", "home_value": 7, "away_value": 4},
        "1ST_shots_on_goal": {"name": "Tirs cadrés 1MT", "home": "3", "away": "2", "home_value": 3, "away_value": 2},
        "2ND_ball_possession": {"name": "Possession 2MT", "home": "67%", "away": "33%", "home_value": 67, "away_value": 33},
        "2ND_total_shots": {"name": "Tirs totaux 2MT", "home": "5", "away": "3", "home_value": 5, "away_value": 3},
    },
    "incidents": [
        {"incidentType": "goal", "time": 23, "player": {"name": "Mbappé"}, "isHome": True},
        {"incidentType": "yellowCard", "time": 31, "player": {"name": "Rabiot"}, "isHome": False},
        {"incidentType": "goal", "time": 44, "player": {"name": "Aubameyang"}, "isHome": False},
        {"incidentType": "yellowCard", "time": 52, "player": {"name": "Vitinha"}, "isHome": True},
        {"incidentType": "goal", "time": 61, "player": {"name": "Dembélé"}, "isHome": True},
        {"incidentType": "substitution", "time": 65, "player": {"name": "Kolo Muani"}, "isHome": True},
    ],
    "h2h": {
        "events": [
            {"homeTeam": {"name": "PSG"}, "awayTeam": {"name": "Marseille"}, "homeScore": {"current": 3}, "awayScore": {"current": 0}, "startTimestamp": 1695000000},
            {"homeTeam": {"name": "Marseille"}, "awayTeam": {"name": "PSG"}, "homeScore": {"current": 2}, "awayScore": {"current": 1}, "startTimestamp": 1679000000},
            {"homeTeam": {"name": "PSG"}, "awayTeam": {"name": "Marseille"}, "homeScore": {"current": 2}, "awayScore": {"current": 2}, "startTimestamp": 1663000000},
            {"homeTeam": {"name": "PSG"}, "awayTeam": {"name": "Marseille"}, "homeScore": {"current": 4}, "awayScore": {"current": 0}, "startTimestamp": 1647000000},
            {"homeTeam": {"name": "Marseille"}, "awayTeam": {"name": "PSG"}, "homeScore": {"current": 1}, "awayScore": {"current": 0}, "startTimestamp": 1631000000},
        ]
    },
    "odds": {},
    "betting": {
        "home_pct": 58.4,
        "draw_pct": 18.2,
        "away_pct": 23.4,
        "signal": "DOMICILE",
        "confidence": 58.4,
    },
}
